openapi: 3.0.3
info:
  title: Vulnerability Tracer Service
  description: Vulnerability Tracer Service
  version: 0.1.0
servers:
  - url: 'http://localhost:10420'
paths:
  /liveness:
    get:
      summary: Check server liveness
      description: >
        Liveness endpoint is used by Kubernetes to determine 
        if the application after startup is still able to serve the requests
      responses:
        200:
          description: Application is running correctly
        500:
          description: Application has a problem that can lead to response errors
  /readiness:
    get:
      summary: Check server readiness
      description: >
        Readiness endpoint is used by Kubernetes to determine 
        if the application finished startup and can serve requests
      responses:
        200:
          description: Application can serve requests
  /api/register:
    post:
      summary: Register service and get vulnerable callables for the microservice
      description: >
        Get vulnerable callables for the microservice and its dependencies,passed as Maven coordinates. 
        Also registers the service if it wasn't registered before, to track the vulnerabilities in its dependencies.
      requestBody:
        description: >
          Microservice's unique identifier and Maven coordinates of its dependencies.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            example:
              serviceName: 'my-microservice'
              dependencies:
                - groupId: 'dom4j'
                  artifactId: 'dom4j'
                  version: '1.6.1'
      responses:
        200:
          description: >
            List of service's vulnerable callables, together with their mitigation strategies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/mock/addVulnerability:
    post:
      summary: Register a mock vulnerability in the database
      description: >
        Add a mock vulnerability to the dependency
      requestBody:
        description: >
          Vulnerability's metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMockVulnerabilityRequest'
            example:
              vulnerabilityExternalId: 'CVE-2018-12345'
              severity: 'CRITICAL'
              dependency:
                groupId: 'org.springframework.boot'
                artifactId: 'spring-boot-starter'
                version: '2.3.0.RELEASE'
      responses:
        200:
          description: Vulnerability added successfully
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/mock/addCallable:
    post:
      summary: Add a vulnerable callable to the dependency
      description: >
        Add a mock vulnerable callable to the dependency
      requestBody:
        description: >
          Vulnerable callable's metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMockVulnerableCallableRequest'
            example:
              packageName: 'nl.tudelft.kponichtera.thesis.microservice.service'
              className: 'DownstreamCallService'
              methodName: 'callFirstService'
              vulnerabilityExternalIds:
                - 'CVE-2018-12345'
              serviceName: 'my-microservice'
              mitigationStrategy: 'ERROR'
      responses:
        200:
          description: Callable added successfully
        400:
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    VulnerabilitySeverity:
      type: string
      enum:
        - 'UNDEFINED'
        - 'LOW'
        - 'MODERATE'
        - 'MEDIUM'
        - 'HIGH'
        - 'CRITICAL'
    MitigationStrategy:
      type: string
      enum:
        - 'NONE'
        - 'ERROR'
        - 'NOOP'
    MavenCoordinates:
      title: Maven coordinates
      type: object
      required:
        - groupId
        - artifactId
        - version
      properties:
        groupId:
          type: string
        artifactId:
          type: string
        version:
          type: string
    AddMockVulnerabilityRequest:
      title: Add mock vulnerability request
      type: object
      required:
        - vulnerabilityExternalId
        - severity
        - dependency
      properties:
        vulnerabilityExternalId:
          type: string
        severity:
          $ref: "#/components/schemas/VulnerabilitySeverity"
        dependency:
          $ref: '#/components/schemas/MavenCoordinates'
    AddMockVulnerableCallableRequest:
      title: Add mock vulnerable callable request
      type: object
      required:
        - packageName
        - className
        - methodName
        - vulnerabilityExternalIds
      properties:
        packageName:
          type: string
        className:
          type: string
        methodName:
          type: string
        vulnerabilityExternalIds:
          type: array
          minItems: 1
          items:
            type: string
        serviceName:
          description: "Name of the service to register the mitigation strategy for. Omit to skip mitigation creation."
          type: string
        mitigationStrategy:
          $ref: "#/components/schemas/MitigationStrategy"
    JavaCallable:
      title: Vulnerable Java callable
      type: object
      required:
        - packageName
        - className
        - methodName
        - mitigationStrategy
        - vulnerabilities
      properties:
        vulnerabilities:
          type: array
          items:
            $ref: '#/components/schemas/VulnerabilityMetadata'
        packageName:
          type: string
        className:
          type: string
        methodName:
          type: string
        mitigationStrategy:
          $ref: "#/components/schemas/MitigationStrategy"
    VulnerabilityMetadata:
      title: Vulnerability metadata
      type: object
      required:
        - severity
        - externalId
      properties:
        externalId:
          type: string
        severity:
          $ref: "#/components/schemas/VulnerabilitySeverity"
    RegisterRequest:
      title: Register request
      type: object
      required:
        - serviceName
        - dependencies
      properties:
        serviceName:
          description: Name of the service to register
          type: string
        dependencies:
          type: array
          items:
            $ref: '#/components/schemas/MavenCoordinates'
    RegisterResponse:
      title: Register response
      type: object
      properties:
        callables:
          type: array
          items:
            $ref: '#/components/schemas/JavaCallable'
    ErrorResponse:
      title: Descriptive error response
      type: object
      required:
        - message
      properties:
        message:
          type: string
      example:
        message: "Error has occurred"